### ISSUE TITLE
R::load() result expected to be empty when $id doesn't exist 

### ISSUE THREAD

**Issue by mauricoder** [gabordemooij/redbean#113]
I'm ussing stable branch. 

On this simple code:

```
    $topic = R::load('topic', $id);
    if($topic)
    {
        // do stuff
    }   
    else
    {
                   // we can't do stuff, bean doesn't exist!
    }
```

$topic allways evaluates to true eaven if $id doesn't exists on table. 

I'm getting an empty Bean, which doesn't evaluates to false on PHP. 

Please correct me if I'm wrong, but looks like the response from load() on not found case isn't the most natural. I found on rb.php line 1742 this code:

```
        if (!$rows) return $bean; 
```

IMHO would be nicer to get a

```
        if (!$rows) return false;
```

Thanks

**Comment by flip111** [comment]
I just noticed for the first time `load` always returns a bean. In my code i never use this feature. That is because after the point in your code (router, session, request data) where you check if it was a create or update action you can just do `R::dispense`. For example when you have a route for `new`. That leaves `load` for the update route where i don't want to create fresh beans at all. I would prefer `null` here, that would be also more in line with other database managers.

About the same topic: https://github.com/gabordemooij/redbean/issues/469
