### ISSUE TITLE
SQL Server support

### ISSUE THREAD

**Issue by groteworld** [gabordemooij/redbean#379]
Is there still SQL Server support? Back in January I saw the addition of SQL Server but it doesn't seem around any more in master. Can anyone point me in the direction of the thought process behind not supporting SQL Server? I'd like to help on this.

**Comment by vzool** [comment]
Sorry, but I founded too in current master repository ^_^

**Comment by alexweissman** [comment]
So, what's the word on this?  Is SQL Server officially supported by RedBean then?

**Comment by gabordemooij** [comment]
There is a SQLServer QueryWriter available in the RB4 master branch,  @ducktype ported it from 3.5 (thank you!) but it has no tests and I fear it is lacking essential methods because it did not get any updates recently.

@diego-vieira is busy writing a new SQLServer QueryWriter and will add some tests. It will be available from the main github repository for your convenience.

@alexweissman Yes  SQLServer is supported 'officially' by the RedBeanPHP community. The community wants this driver and maintains it. It will not be part of the all-in-one package on the website because I only allow the 3 most popular database platfroms (to reduce filesize).

**Comment by vwroad87** [comment]
Hello I have been trying various semi-examples of rb.php with ms sql server and have not been able to establish a connection?  It seems all the code I've been able to pull is missing this function in their implementations which I have "patched" locally.
QueryWriter::addUniqueIndex

I've pulled both SqlsrvQueryWriter.php and sqlserver.php

Could someone please point to versions of rb.php, a working querywriter implementation and an basic connect example with redbean?   

FYI I do have a ms sql server working correctly with php and sqlserver_connect().

Thanks

dp
