### ISSUE TITLE
Support composer

### ISSUE THREAD

**Issue by fracz** [gabordemooij/redbean#402]
I wonder why this package is not published on https://packagist.org/? Only the 3.5.1 version is available.

**Comment by eddieajau** [comment]
> https://packagist.org/packages/narrowspark/redbean

This doesn't seem to be supported anymore. https://github.com/simirimia/redbean may be a better option.

The problem with composer is simply the naming of the tags. See https://packagist.org/about (under _Managing package versions_).

If you name the tags `v4.0.0` instead of `v4.0`, Composer will be happy.

**Comment by eddieajau** [comment]
And obviously you need to tag each patch. So if you could either back date a `v4.1.4` tag, or make sure when you release `v4.1.5` you tag the repository, everything will work nicely.

**Comment by gabordemooij** [comment]
ok thanx for the info, I will give it a try
