### ISSUE TITLE
Missing unique key on many-to-many table (MySQL)

### ISSUE THREAD

**Issue by czarnecki** [gabordemooij/redbean#412]
In the documentation:
> Also note that a shared list cannot have aliases and always applies a UNIQUE constraint (you cannot have duplicate links).

My code:
```php
$staff = R::dispense('staff');
$role = R::dispense('role');
$staff->sharedRoleList[] = $role;
R::store($staff);
```

and the table created by Redbean:
```sql
CREATE TABLE `role_staff` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(11) unsigned DEFAULT NULL,
  `staff_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_for_role_staff_role_id` (`role_id`),
  KEY `index_for_role_staff_staff_id` (`staff_id`),
  CONSTRAINT `role_staff_ibfk_2` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `role_staff_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

According to the documentation the unique index on (role_id, staff_id) should be created or I am wrong?

**Comment by gabordemooij** [comment]
The AssociationManager will create the UNIQUE constraint the second time, because it has to inspect the table structure of the existing table (this is an implementation detail). The AssociationManager has to determine whether the link table consists of link records only, if it has additional columns (>3) the UNIQUE constraint will not be created because you might want to use the constraint on more columns in that case (or none at all).

**Comment by gabordemooij** [comment]
In the new master this has been changed, the Association Manager will now create the unique constraint immediately. So, this will soon be a thing of the past.
