### ISSUE TITLE
Integer/Double detection

### ISSUE THREAD

**Issue by jamesjnadeau** [gabordemooij/redbean#423]
Love  this project, excellent work! I'm using it to quickly setup a project I'm working on and I ran into the following scenario. Might be an issue, or a trade off, not sure. Just letting you know what I found.

I'm using postgresql, and while starting a new table, I was adding fields with the following example values:

    1.000
    2.000
    3.000
    etc...

these values are added to the bean using the ->import() function.

this gives me back an error:

    <b>Fatal error</b>:  Uncaught [22P02] - SQLSTATE[22P02]: Invalid text representation: 7   ERROR:  invalid input syntax for integer: &quot;1.000&quot;
    trace: #0 /home/codio/workspace/rb.php(785): RedBeanPHP\Driver\RPDO-&gt;runQuery('INSERT INTO &quot;pl...', Array)
    #1 /home/codio/workspace/rb.php(808): RedBeanPHP\Driver\RPDO-&gt;GetAll('INSERT INTO &quot;pl...', Array)
    #2 /home/codio/workspace/rb.php(3113): RedBeanPHP\Driver\RPDO-&gt;GetCol('INSERT INTO &quot;pl...', Array)
    #3 /home/codio/workspace/rb.php(4126): RedBeanPHP\Adapter\DBAdapter-&gt;getCell('INSERT INTO &quot;pl...', Array, 0)
    #4 /home/codio/workspace/rb.php(4306): RedBeanPHP\QueryWriter\AQueryWriter-&gt;insertRecord('planfee', Array, Array)
    #5 /home/codio/workspace/rb.php(6839): RedBeanPHP\QueryWriter\AQueryWriter-&gt;updateRecord('planfee', Array, 0)
    #6 /home/codio/workspace/rb.php(6403): RedBeanPHP\Repository\Fluid-&gt;storeBean(Object(RedBeanPHP\OODBBean))
    #7 /home/codio/workspace/rb.php(6803): RedBeanPHP\Repository-&gt;store(Object(RedBeanPHP\OODBBean))
    #8 /home/codio/workspace/rb.php(6924): RedBeanPHP\Repository\Fluid in <b>/home/codio/workspace/rb.php</b> on line <b>636</b><br />

I was easily able to work around this, by changing the values I'm sending to be:

    .001 etc...

So this isn't a show stopper :) I'm just wondering, what you think about detecting the precision up front? I'll totally accept this as a will not fix... as it's super easy to work around.

The values I passed in were most definitely sourced from strings. Maybe this contributes to the issue.

As a user of this library, and all it's awesomeness, I would expect by passing in a value with a specified precision, the column should be auto sized to fit the data I'm passing in. 

I imagine that something that is auto checking the columns current type is making an assumption that '1.000' is an integer, and then going along it's merry way to try and pass this into the query, and postgre chokes on it. 

Can you point to the spot in the code where you think is causing this? 

If I don't hear back from you I'll investigate further when I find the time :)

Thanks in advance for your time!

**Comment by gabordemooij** [comment]
Hi, 

Yes, I know about this issue. Try the follow code snippet and see what happens:

    $bean = R::dispense('bean');
    $bean->value = 1.00;
    R::store($bean);
    print_r(R::inspect('bean'));
    $bean->value = 1.02;
    R::store($bean);
    print_r(R::inspect('bean'));

See? RedBeanPHP will adjust. The problem is that RedBeanPHP can't tell what you mean when you send 1.00, do you want a double or did you calculate something and forgot to cast to integer? It also sees that 1.00 equals 1 and because INT requires less space than DOUBLE and you can always update from INT to DOUBLE (but not the other way around) it decides to use INT instead of DOUBLE. However as soon as you send a value that does not fit into INT it will change the column to DOUBLE. Even better, if you prefix your value like this: 01.00 it will update your column to TEXT because it wants to preserve the first '0', it might be a telephone number for instance. 

Maybe this algorith could use some additional refinement. Any ideas are welcome ;)

Here is the code that's responsible for this behavior:

    if ( $this->startsWithZeros( $value ) ) return self::C_DATATYPE_TEXT; 
    if (
     $value === FALSE //we dont use booleans because psql has no auto-cast for them
    || $value === TRUE 
    || $value === NULL 
    || ( $value instanceof NULL ) //Hm, I think this check is redundant...
    || ( is_numeric( $value )
      && floor( $value ) == $value
      && $value < 2147483648
      && $value > -2147483648 )
    ) {
      return self::C_DATATYPE_INTEGER;
    } elseif ( is_numeric( $value ) ) {
      return self::C_DATATYPE_DOUBLE;
    } else {
      return self::C_DATATYPE_TEXT;
    }


Hope this helps to understand the results, and maybe we could improve this code somehow. As I said I'm open to suggestions!

cheers
Gabor

**Comment by gabordemooij** [comment]
Fixed it.

https://github.com/gabordemooij/redbean/commit/206a07bbf845e1efd1fae60035e9279e868cbb73

**Comment by jamesjnadeau** [comment]
Thank you so much!

**Comment by gabordemooij** [comment]
No problem :)
