### ISSUE TITLE
Add support to SQL Server to RB4

### ISSUE THREAD

**Issue by diego-vieira** [gabordemooij/redbean#426]
Hello @gabordemooij I while back I added support for SQL Server to RB 3 and I would like to do the same for RB4, but this time make it part of the core.

As long as I write the tests, it'll be ok to add to the core?
Thanks

**Comment by gabordemooij** [comment]
What do you mean by core? It can be a QueryWriter just like the others, no problem. As long as the code quality is ok and there are tests it will be fine. It will not be included in the all-in-one package on the website though since I want to keep that file small (and only support the most popular PHP databases: MySQL/MariaDB, Postgres and SQLite), CUBRID is also not part of this package.

**Comment by diego-vieira** [comment]
Awesome, sounds good.
I'll get it done and get back to you when it's ready.

Thank you!

**Comment by gabordemooij** [comment]
Hi, @ducktype ported the 3.5 SQLServer to RB4, maybe you can use that as a basis?

**Comment by gabordemooij** [comment]
https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/QueryWriter/SQLServer.php

**Comment by vwroad87** [comment]
Diego,  thanks so much to you for this query write.

Can you please tell me how to "install" this in my version of RebBean

**Comment by mattymaloney** [comment]
Is there any updated QueryWriter available for sqlsrv?
