### ISSUE TITLE
ms sql and redbean example setup()  / connect()

### ISSUE THREAD

**Issue by vwroad87** [gabordemooij/redbean#432]
Hello I have been trying various semi-examples of rb.php with ms sql server and have not been able to establish a connection? It seems all the code I've been able to pull is missing this function in their implementations which I have "patched" locally.
QueryWriter::addUniqueIndex

I've pulled both SqlsrvQueryWriter.php and sqlserver.php

Could someone please point to versions of rb.php, a working querywriter implementation and a basic connect example with redbean?

FYI I do have a ms sql server working correctly with php and sqlserver_connect().

Thanks

dp

**Comment by gabordemooij** [comment]
I will remove this driver because I can't guarantuee its quality.

**Comment by gabordemooij** [comment]
I also HATE MICROSOFT. It's a criminal organization and anyone using their products is a complete and utter idiot.

**Comment by vwroad87** [comment]
easy there,  we are just technologist trying to help people understand data, we don't get to make business decisions or political decisions.   as much as you hate MS they have forced open source into being,   no light without dark....   really chill a bit,   are you gonna stop supporting intel hardware too?

**Comment by gabordemooij** [comment]
Sorry for the reaction, I need to ventilate some of the frustration I have with companies like Microsoft.

On a practical note, it's very hard to support OCI, DB2 and SQLServer. They are not freely available and they are 'hard to install' due to their proprietary nature. This means I can't answer any questions I get about these drivers. I recommend to create a fork, this way people asking questions about the details of this driver can visit the corresponding repo.

**Comment by vwroad87** [comment]
No worries,   there is so much work to do in this field I just don't have
time change out clients complete infrastructure just to help them with
their data.

I you know of anyone with a successful effort going on via RB and ms sql I
would appreciate a link.

I'm more that willing to do the testing on ms sql 2008 R2, just can't get
past "setup()".

dp
