### ISSUE TITLE
Bean property types

### ISSUE THREAD

**Issue by vojtechkral** [gabordemooij/redbean#448]
Hi,
  I noticed recently all properties on my beans are strings, even those I've checked are integer in the database, such as `id` and others. Is this to be expected?

**Comment by gabordemooij** [comment]
Yes, when retrieving a bean from the database, all properties are converted to strings.
This is because in RedBeanPHP the types in the table can change due to fluid mode, therefore they are standardized as strings. In practice this does not matter: since PHP is weakly typed you can just use the weak comparison operator '=='. This has been designed this way.

**Comment by vojtechkral** [comment]
Okay. I frequently serialize beans into JSON where I need the correct type, but it's not really a problem, I can simply cast to the right type. Thanks for info.
