### ISSUE TITLE
Add Signify / GnuPG signatures to download package

### ISSUE THREAD

**Issue by 0x13a** [gabordemooij/redbean#450]
Please, could you implement namespacing for this library ? If anyone has to include in a project is bad practise load single file to use the library.

**Comment by r3wt** [comment]
@diegomariani if you're using HHVM or any type of opcode cache, you shouldn't worry about it being a single file. at any rate, the library is over 12,000 lines long, so if you want to fork it and namespace it out its going to be a fairly massive undertaking.

**Comment by simirimia** [comment]
Actually you don't need to use the singe-file distribution. You could clone the repository and use it directly. ReadBean is developed "the typical way" with one file per class, namespaces matching the directories and so on. 
If you use composer, you can add RedBean and get the namespaced, multi-file version. If you're confident using dev-master: https://packagist.org/packages/gabordemooij/redbean, or you could use my fork where I only added the composer.json : https://packagist.org/packages/simirimia/redbean, https://github.com/simirimia/redbean. There you get some  stable versions as well.

**Comment by simirimia** [comment]
Ah, update: since 4.2 is released you get stable version here as well: https://packagist.org/packages/gabordemooij/redbean -> so no more need for my fork

**Comment by r3wt** [comment]
@simirimia If installing via composer can we still use everything as `R` alias ???

**Comment by tleb** [comment]
@r3wt If you look at the [composer.json](https://github.com/gabordemooij/redbean/blob/ea3f70175178d5385d45c83a32efa51495f80b0c/composer.json#L17-L21), you will see that the namespace `RedBeanPHP\` is autoloaded. Then, if you go in this `RedBeanPHP/` folder, you will see a [R.php file](https://github.com/gabordemooij/redbean/blob/d8f9f4f5ab01b285a587dd54f5175d013c316ade/RedBeanPHP/R.php#L6-L10), which means that the `R` facade is just in the namespace `RedBeanPHP\`.

**Comment by gabordemooij** [comment]
Personally I use the one-file solution for all my projects.
It might be bad practice but it's damn easy, and I have never heard anyone complain, nor did it cause any bugs or conflicts.

**Comment by tleb** [comment]
Do you not use Composer in your project? It really is powerful to manager dependencies.

**Comment by r3wt** [comment]
@tleb so how would i alias RedBeanPHP to R ?

say i have a class like

Class DB {}

and in it i reference redbean  lik `\R` 

how can i set that alias  in my class? `\RedbeanPHP\R` becomes `\R`

**Comment by tleb** [comment]
```php
// You could call R directly
\RedbeanPHP\R::freeze(true);

// Or use `use`
use RedbeanPHP\R;
R::freeze(true);

// Or use an alias
use use RedbeanPHP\R as Redbean;
Redbean::freeze(true);

// Or create a facade of the R facade
class R extends \RedbeanPHP\R {}
```

**Comment by r3wt** [comment]
i just used `class_alias('\RedBean\R','\R');` and it worked fine.

**Comment by gabordemooij** [comment]
I never use composer. I never even use apt-get, yum, npm or any other kind of dependency resolution. Good software has no dependencies other than an OS / VM.

**Comment by r3wt** [comment]
I understand where you are coming from Gabor, but our jobs depend on is to be agile-- that is to say, we must get alot done I short periods of time. Now I could spend time wget'ing, untaring,and requiring red bean manually, but it makes more sense to just type composer install.

**Comment by tleb** [comment]
@gabordemooij Do you know that what you are saying goes against the Unix philosophy:

```
Write programs that do one thing and do it well. Write programs to work together.
```

Tools such as `composer`, or `apt-get`, or any dependency manager, try to make it simpler to link programs together, so that programs can focus on what they must do, and so that they can do it well. If we created the same thing over and over again, every single project would fail, because they would need to do everything from scratch, even though people already created those required programs. Dependency managers are tools to build upon, they are made to create good software based on other software which achieve the task they are asked to almost perfectly.

**Comment by nuxwin** [comment]
@gabordemooij

You should be killed. Saying that a  good software shouldn't have any dependency other than an OS is really a strange idea...  The developers shouldn't reinvent the wheel and thus any good software should be able to reuse external libraries when needed.

**Comment by gabordemooij** [comment]
@tieb composer does not link programs, it links libraries. And, as such it creates huge programs that do everything - which is basically the opposite of the UNIX philosophy. Apt-get also rarely installs programs, it installs mostly lib-this, lib-that, lib-different-version etc. Programs relying on a ton of external libs are definitely not 'Unixy'.

@nuxwin I did not say developers should re-invent the wheel. Neither is this an inevitable consequence of having no dependencies. I simply believe a well designed base system would be preferable - but that's harder to build. 

@nuxwin Please, let's refrain from statements like 'should be killed' and keep the discussion civilized. Open source forums are already famous for their anti-social tone. We're just people and everyone is entitled to his/her own opinion. If someone disagrees there is either an opportunity to improve knowledge or exchange new ideas.

Also - I believe I accidentally sidetracked this thread with my comment about dependencies in general, sorry for that.

**Comment by nuxwin** [comment]
@gabordemooij

Don't get bad ;) This was just an expression.

**Comment by gabordemooij** [comment]
@nuxwin ok, no problem

**Comment by x-yuri** [comment]
@gabordemooij, well, I'm curious, and not sure I got the point. You believe all the libraries belong to the base system? And hence good software is impossible with bad base system?

**Comment by tleb** [comment]
I -too- would like to continue this debate but I do not think a Github issue is the best place for this. If anyone could recommand a more appropriate place for this (an IRC channel, a website ?).

**Comment by diegomariani** [comment]
@tleb maybe there --> http://www.php-fig.org/irc/

**Comment by x-yuri** [comment]
Well, it's not that I was going to debate on this. I rather wanted to clarify @gabordemooij's point of view. For now it seems self-contradictory to me.

**Comment by gabordemooij** [comment]
@x-yuri I acknowledge sometimes you can't do without dependencies. But I believe people have given up to early on the problem. Often when you install dependencies you end up with all kinds of stuff you don't want and you lose control to a certain extend. I believe that we, as a community should invest more in solid base systems. I admire Linux distros like Slackware that have a rich package repo with very few dependencies. I think we should try harder to get our 'bases right' instead of trying to fix fundamental problems with tooling.

Also, I hate the fact, I can't just grab a lib from the web anymore because some of them seem to be tied pretty closely to the whole composer workflow, they have no standalone tarballs, they need autoloader this and that... But I have to admit I am very conservative and stubborn in some matters. There's lots of other issues as well, composer uses git/github as repositories, interfering with my use of it as a version control system (preferred layouts) etc etc..

Please note that when I say things like 'Good software should this or that...' it's just my opinion, I do not expect everyone to agree. However I would like to discuss the usefulness of composer, unfortunately, as soon as you 'ask questions' or 'criticize' a popular technique you're considered to be 'a moron'. These discussions seem to end up in complete flame wars and honestly as long as that culture persists I don't feel compelled to explain every decision I make (luckily the RedBeanPHP forum is quite civilized though).

**Comment by sbrl** [comment]
I've ended up using composer simply because I find it a challenge to keep my dependencies up-to-date. I don't have a lot of them, but  when you have lots of projects, it starts to quickly get out of hand.

**Comment by gabordemooij** [comment]
@sbrl don't use composer. Just don't. If you cannot manage your dependencies you have a very big problem and composer hides it. Updating bad code in zillions of libs will not magically improve the reliability and security of your code.

- get rid of all libraries that are not crucial
- remove all libs with dependecies, they are by definition created by idiots
- keep things simple, if you need that much libraries, you failed at keeping things simple

**Comment by suicane** [comment]
I don't do this usually but I had to screenshot this whole discussion. Guy doesn't use namespaces, uses single file for his projects and he bashes the practice of tracking your dependencies with - listen to this  - **programs**.  If anyone stumbles upon this page via google, please take time to read what @gabordemooij wrote and take note - NEVER justify your bad decisions by making stuff up.

**Comment by paragonie-scott** [comment]
> don't use composer. Just don't. If you cannot manage your dependencies you have a very big problem and composer hides it. Updating bad code in zillions of libs will not magically improve the reliability and security of your code.

As a security engineer who works primarily in PHP and contributes to open source cryptography libraries for the PHP community, I [strongly disagree and say that using Composer is a ***damn good* idea**](https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software#dependency-management).

> Updating bad code in zillions of libs will not magically improve the reliability and security of your code.

Uh, yes, it will!

Outdated third-party libraries with known (i.e. not zero-day) vulnerabilities are one of the most reliable RCE vectors when testing a system. (Aside: Thank you, projects that ship their own PHPMailer bundles, for all the easy footholds into otherwise challenging networks to penetrate.)

This isn't intuitive for most people, so I've laid out [the case for automatic security updates](https://paragonie.com/blog/2016/10/guide-automatic-security-updates-for-php-developers#why-automatic-updates) before.

Composer makes it easier for projects to keep dependencies up-to-date. This creates a measurable improvement to the security and stability of real world systems.

**Comment by gabordemooij** [comment]
Updates often introduce new bugs and new vulnerabilities. So your just replacing old bugs with new bugs. Only right after an update 'you consider your software safe', but as time progresses it turns out the initial update was not safe at all but by then most developers pretend the software 'is now suddenly unsafe because it is old' - that's not true, it was already compromised right after the update. Besides that, dependency management systems make it worse, because you don't even know what you install anymore. There may be even some toxic packages among the dependencies:

https://news.ycombinator.com/item?id=15272394
https://news.ycombinator.com/item?id=11340510
https://sensorstechforum.com/arch-linux-aur-repository-found-contain-malware/

While I don't pretend that bug-free software can be written, a better solution might be to focus on simplicity. Dependency management systems compromise simplicity because they make it easy to solve the natural issues regarding dependencies. In a sense, they hide complexity - and paradoxically therefore they increase the risk of importing new bugs and vulnerabilities.

So, I reverted the commit that removed the Composer file because, even though I am against it, I also don't really care, I just get a bit angry when Composer related problems (like what version string to use) creep into the RedBeanPHP repository. 

And yes, you make screenshots all you want and laugh about RedBeanPHP or me. I don't give a shit. Have fun.

BTW, remember that this is an open source project, so you can fork and nobody is forcing you to use RedBeanPHP so, if you don't like it:

https://www.doctrine-project.org/

bye bye!

**Comment by hparadiz** [comment]
Literally everything you just said can apply to any dependency manager including Git, Github, apt, whatever.

How are redbean releases more secure than another PHP library? They aren't. You aren't signing your releases and there's no verification system in place. The fact is humans make up the "PHP community" and it's up to us to verify security. And as far as human verification goes I'll trust the millions of users of a given popular package on packigist versus having to manually check the Git of a project like yours. 

Honestly though just looking at your source tree your ORM is straight out of PHP 4.x times. Your project has a custom unit testing schema because apparently PHPUnit isn't secure enough? You have no `spl_autoload_register` anywhere in your code even though it makes sense here to use it. You're still publishing redbean on packigist with a composer.json. So I guess "trust me" but no one else is enough for you. Like honestly wtf even is [this](https://github.com/gabordemooij/redbean/blob/master/p533patch.php)? You can't even generate code coverage reports because of your home baked unit testing system which I'm sure doesn't support clover.xml output for code coverage. Which is why you don't have a code coverage badge.

Yea yea packigist needs signed releases to give it some "security" but honestly the fact is the market has moved on.

In most PHP shops these days it's about speed & quantity of code / features over "security" concerns.

Why would I implement AWS myself when they give me a library to use? Why would I implement the Fitbit API manually when [someone already wrote one](https://github.com/djchen/oauth2-fitbit)? Especially when it comes with unit tests and lots of users who will call stuff out if it breaks or is compromised.

We're all idiots? Really dude? The company I work for and all the jobs under it could literally not exist without the good work put in by hundreds of developers I've never met. Because it's literally impossible for me to sit down and write an API implementation for every service we interact with. And yet we are currently running a company based on tying all these things together into a coherent service.

I think you seriously need to re-evaluate your philosophy and take a look at a lot of the [good](https://thephpleague.com/) work being done currently in the PHP space by dedicated people.


And finally. If you care sooooo much about security maybe it's time to upgrade to PHP 7.1 because security support for 5.6.x ends in 3 months.

**Comment by gabordemooij** [comment]
> Literally everything you just said can apply to any dependency manager including Git, Github, apt, whatever.

Git is a VCS, Github is a code hosting platform, so these are not DMs. And yes, it applies to apt. That's why I recommend to use Slackware, Crux or *BSD instead.

> How are redbean releases more secure than another PHP library?

1. 180000+ tests
2. 10 years of maturity
3. Careful code review process
4. Focus on eliminating code, simplicity (minimalism)
5. 0 dependencies

Updating RedBeanPHP is also easy: just copy-paste the rb.php file and done!

> You aren't signing your releases
I provide sha256 checksums on the download page:
https://redbeanphp.com/index.php?p=/download
So you can check whether the downloaded file has not been corrupted or modified - improvements can be made here.

>  I'll trust the millions of users
You use Windows I suppose (millions use it!) ? Seriously. How on earth does quality improve just by USING something?!

> your ORM is straight out of PHP 4.x times
Therefore it must be bad. Because new is always better? 

> Why would I implement AWS myself when they give me a library to use?
AWS is a platform, not a library. You can't implement AWS with just a library.

> We're all idiots? Really dude?
I don't know about the rest in this thread but you seem to suffer from the Dunning–Kruger effect:
https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect

> You suffer from NIH syndrome
To a certain extend agreed, and how do you think I that happened after 20 years of coding?

> I'll just kindly ask you, just ASSUME you might be wrong
That's all I ever do. I know I might be wrong. But to be sure I need good arguments.

> Should I rewrite those primitives and libraries to deal with SAML and OAuth2 so I'm "safe" 

Never use OAuth:
https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529

Never roll your own crypto. 
Use a libreSSL-based crypto solution:
https://www.libressl.org/

**Comment by paragonie-scott** [comment]
Sha256 isn't a digital signature.

https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded

**Comment by hparadiz** [comment]
```
How are redbean releases more secure than another PHP library?
> 1. 180000+ tests
> 2. 10 years of maturity
> 3. Careful code review process
> 4. Focus on eliminating code, simplicity (minimalism)
> 5. 0 dependencies
```
This is seriously your answer? You demonstrate a lack of understanding of what actually makes a package manager have "secure" releases. A secure release is signed with a private key that only you would have. At the moment anyone can get into your Github user and commit anything they want to your project. Sure you can revert it once you get your account back but until then damage can be done.

Your hashes mean nothing. Anyone can edit your website and edit those hashes anytime they want. None of what you mentioned gives increased security.

I also have a 10+ year old ORM with hundreds of projects and more then a decade of maturity. But you know what? Nobody cares.

If you have no code coverage report your tests mean nothing.

Never use oauth? lmao. The company I work for. Literally our entire business model depends on APIs that use oauth. I have no choice. It's not like oh lemme just make my own Fitness tracker real quick.

This entire thread can be summed up as "I made up my mind 10 years ago and I don't feel like learning anything new so leave me alone".

**Comment by brunocassol** [comment]
This issue was closed 3 years ago. Why resurrect something just because someone on the internet does things differently? Apparently [someone posted](https://www.reddit.com/r/PHP/comments/9edtkx/if_you_cannot_manage_your_dependencies_you_have_a/) this issue on /r/php, what could could come out of this?

I'm a composer user but I don't go out of my way trying to hammer into people's mind that they should do things differently. There are already forks with composer support anyway. Just move on people. This is borderline harassment at this point.

Thank you for writing RedBean @gabordemooij ❤

**Comment by gabordemooij** [comment]
Anyway, as I already admitted you're right concerning the checksums, it only protects against accidental corruption. I will use signify() to sign the releases in the future. 
https://man.openbsd.org/signify

**Comment by paragonie-scott** [comment]
Okay. There's little left to discuss then, it may be a good idea to lock this thread to only collaborators.

**Comment by gabordemooij** [comment]
That was a good idea. Hopefully we can now continue the discussion in a more fruitful way.

**Comment by gabordemooij** [comment]
I just discovered signify() is OpenBSD-only, so I'll use GnuPG signatures instead. The signatures will be uploaded to github and the google groups forum. That way, to fake the sigs you must hack the RedBeanPHP website, Github and Google at the same time. Do I miss something here?

**Comment by gabordemooij** [comment]
Files now contain Signify signatures. GnuPG may follow later.
