### ISSUE TITLE
allow underscore and period in table names

### ISSUE THREAD

**Issue by r3wt** [gabordemooij/redbean#454]
it's weird that you can't do this. now i sometimes end up with table names like

grouptype
groubsubgroup
groupadministrator
groupsubgroupadministrator

etc

total PITA to read. The one blight on an otherwise awesome library

**Comment by gabordemooij** [comment]
This is a very old topic, the easiest way to solve this however is to come up with better names for your concepts. Most of the time, these kind of 'systematic combinations' can be replaced with far more descriptive nouns.

**Comment by gabordemooij** [comment]
I do not have enough knowlegde of your domain, but here is an example in one of my apps:

user (a user)
userinfo (the details of the user in the system)
workuser (a user working for the company)
projectuser (a user, working for the company involved in a project)

we renamed these to:

user
account
employee
participant

Just for the inspiration...
As a matter of fact, the latter group of names is also easier to remember because they are less 'abstract' and a little more 'colorful'.

cheers
Gabor

**Comment by r3wt** [comment]
@gabordemooij I generally like to name tables in a way that shows their relation... it helps me remember the relations. so i can code without having to recall the table name.
