### ISSUE TITLE
Insert beans where id != 0 (or NULL)

### ISSUE THREAD

**Issue by alexandr-san4ez** [gabordemooij/redbean#521]
Hello.

I'm trying to add a record to the table but instead of **"INSERT INTO .... "** receiving **"UPDATE table SET  cost = 1  WHERE id = 4"**.

Example code:
`$bean = R::getRedBean()->dispense('table');`

`$bean->id = 4;`
`$bean->cost = 1;`

`R::store($bean);`

Can I create a forced entry?

Thanks.

**Comment by gabordemooij** [comment]
RedBeaPHP will only insert beans that have no ID yet.
You cannot force RedBeanPHP to use a specific ID because it's the primary key. If you want to generate a special type of ID take a look at the UUID section.

**Comment by razvanioan** [comment]
I've just hit my head on this one too, and it hurts !

I have mixed tables (with regular / integer auto-incremented ID's & UUIDs generated on client-side stored as `binary(16)` for better optimisations)

I actually haven't understood exactly the example from UUIDs section, so I'll have to use `R::exec('INSERT INTO ...')` in order to make it work ...

I loved R for simplicity, but having support for custom / manual ID on insert should be important, so I'll have to reconsider it in the future !
