### ISSUE TITLE
return proper types for int column

### ISSUE THREAD

**Issue by alzalabany** [gabordemooij/redbean#559]
even though that id was created by redbean as Int autoincrement, it still return value as string which is causing some problem when used in restful api due to improper types.

```
$user = R::dispense('user');
$user->name = 'test';
R::store($user);
-----
$user = R::load('user',1);
var_dump($user->export());
 --> will output
array(18) {
  ["id"]=> string(1) "1"
  ["name"]=> string(1) "test"
}

```

**Comment by gabordemooij** [comment]
Due to the architecture of RedBeanPHP this is not possible as it requires the library to keep track of your data types in the database and that would open up all kinds of new problems.

Note that RedBeanPHP has been designed as an ORM within the context of a dynamically typed language: PHP - hence the name. Therefore it assumes the type information is for the most part irrelevant.

Also see (regarding mismatches between DB types and PHP types):
http://schlueters.de/blog/archives/182-Types-in-PHP-and-MySQL.html

You can either post-process the JSON structure recursively with an array_walk statement or just send strings. My own APIs mostly send back strings, because that just works fine, never had any problems. Sometimes this is not enough though. It all depends on context.
