### ISSUE TITLE
Allow detecting lock wait timeout in loadForUpdate()

### ISSUE THREAD

**Issue by dominics** [gabordemooij/redbean#575]
I'm having trouble telling the difference between two underlying situations when using `loadForUpdate()`:

1) The bean being loaded doesn't exist in the database
2) The bean being loaded does exist in the database, but was locked by another process, and we couldn't obtain the lock (e.g. within the `innodb_lock_wait_timeout`)

Both of these have the same behaviour of returning a new empty bean. This is convenient for the first case (and I can detect it in a number of ways and substitute my own behavior, if necessary). But it's extremely inconvenient for the second case.

If you're using a function expected to acquire a lock when the row exists (as `loadForUpdate()` does), there should be some way for the user to detect when that lock acquisition has failed. (Probably via an exception, which has the advantage of automatically rolling back any enclosing transaction by default but remains configurable).

So, this is a feature request to allow configuring `loadForUpdate()` to throw exceptions specifically in the case of "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction"

**Comment by gabordemooij** [comment]
As already mentioned in the PR, passing the error is fine, but we can also just throw exceptions instead of returning empty beans if we detect loadForUpdate has been used instead of load because there is no scenario where you want an empty bean in case of an update (I think...).

**Comment by gabordemooij** [comment]
I changed the R::loadForUpdate() to always throw instead of returning an empty bean. I think this is a more elegant solution as we do not have to check DB specific error codes at all. I propose to revert your error code checking and just make loadForUpdate() always throw and Exception instead (this is now also a parameter of load()). This is also easier to test and does not require every QueryWriter to comply, lowering the threshold for devs that create new Writers.

**Comment by gabordemooij** [comment]
Hm, this is more complex than I anticipated. I propose to keep your code and just make loadForUpdate throw exceptions by default. Seems the best of both worlds.

**Comment by dominics** [comment]
Sounds great!

**Comment by gabordemooij** [comment]
So I removed the detection code in both repositories. In fact the logic is fairly simple: in fluid mode you want an empty bean if the bean cannot be found and an exception otherwise unless the exception complains about a missing table or column. In frozen mode it's almost the same, except that missing tables and columns are no longer ignored. Because 'lock timeouts' are not 'missing structures' this will now lead to an exception by default.

**Comment by gabordemooij** [comment]
Can you verify this solution? Do you agree?
