### ISSUE TITLE
Allow getting driver-specific error code from exceptions

### ISSUE THREAD

**Issue by dominics** [gabordemooij/redbean#576]
The `runQuery()` method in `RPDO` throws away the original `PDOException` at [around line 191](https://github.com/gabordemooij/redbean/blob/e5e9409dc7b00a2d9d9199479f53193286059788/RedBeanPHP/Driver/RPDO.php#L191) instead of passing it as the "previous" (causing) exception (i.e. the third argument to the constructor of `RedBeanPHP\RedException\SQL`).

This is annoying because it throws away some valuable information - whereas if there was still a reference to the `PDOException`you could get at that info with just `$sqlException->getPrevious()->errorInfo`

Specifically, I'm thinking of "general errors" which in MySQL all have the "sql state" error code of `HY000`, even though there are dozens of them for very different causes (from invalid input/strings, disk full, failure in underlying storage engine (i.e. innodb) or just lock wait timeout like in #575) - keeping the reference to the PDOException allows getting at the 'driver-specific' error code.

So, for example, in an error like: "SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine", not throwing away the original PDOException would allow structured access to the actually useful error number `1030`, not just `HY000` (in fact, this seems to be the main error code used in other DBALs e.g. https://github.com/doctrine/dbal/blob/90cf171c0a8867f3d28398ace24bd238e4b810b3/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php#L45)

**Comment by gabordemooij** [comment]
I changed the R::loadForUpdate() to always throw instead of returning an empty bean. I think this is a more elegant solution as we do not have to check DB specific error codes at all. I propose to revert your error code checking and just make loadForUpdate() always throw and Exception instead (this is now also a parameter of load()). This is also easier to test and does not require every QueryWriter to comply, lowering the threshold for devs that create new Writers.

**Comment by gabordemooij** [comment]
Hm, this is more complex than I anticipated. I propose to keep your code and just make loadForUpdate throw exceptions by default. Seems the best of both worlds.

Too bad you cant merge issues in github, now I have to keep these in sync ;)

**Comment by gabordemooij** [comment]
Okay, I tried to simplified the whole thing again:

If a bean does not exist, R::load() and R::loadForUpdate() will return an empty bean.

If there is an error because of a missing table or column, both methods will return an empty bean in fluid mode and throw an exception in frozen mode.

If something else happens (lock timeout for instance) both methods will always throw an exception, even in fluid mode.

How does that sound?

**Comment by Lynesth** [comment]
Does that mean that we have to change our code if updating to no longer check for ```$bean->id == 0``` when we load a bean that doesn't exist ?
