### ISSUE TITLE
Do I have to always unbox() a SimpleModel when working with an x-own-list?

### ISSUE THREAD

**Issue by krisives** [gabordemooij/redbean#578]
Sometimes I can't do this:

```
function blah(SomeBean $x, OtherBean $y) {
    $x->xownOtherList[] = $y;
    R::store($x);
}
```

But it works when I do the same thing with unboxing:

```
function blah(SomeBean $x, OtherBean $y) {
    $z = $x->unbox();
    $z->xownOtherList[] = $y;
    R::store($z);
}
```

`SomeBean` and `OtherBean` are example names here the real names are simple single words.

**Comment by gabordemooij** [comment]
Yes, boxing will turn a bean into a model while unboxing will give you all the bean functionalities.

**Comment by krisives** [comment]
Do own-list and x-own-list still work from a model? It seems like they do, when I do things like `$someModelObject->ownThingList` it's able to access the data. If this is well documented somewhere I will gladly read the docs, but I have read the documentation for models and it's a bit scarce.

Thank you for all your help!

**Comment by gabordemooij** [comment]
I will review the documentation and extend it!

**Comment by krisives** [comment]
@gabordemooij In 10678f1 you mention:

>  While some functionality (like magic get/set) is available in the model, this is just read-only.

I can't see why this is true, since `__set` does a `$this->bean->$prop = $value`

Thank you for any assistance.

**Comment by Lynesth** [comment]
It's actually not working because `__get()` isn't returning a reference to the list, so you're not actually adding anything to it.

When working with bean properties which are arrays (such as an ownList), `__set()` is never called unless you actually modify the property itself (doing `$bean->xownOtherList = $something` for example).

In your case, what happens is `__get()` is called, and then some operation (adding something to it) are made on that array. But this is just a copy of the ownList the bean is actually holding, not a reference to it.

Changing the magic `__get()` to this

```php
public function &__get( $prop )
{
    return $this->bean->$prop;
}
```

should make it work but may break some other things.

I would advise not to do so and unbox your beans or - if inside the class model - use $this->bean.

**Comment by krisives** [comment]
Thank you, I don't want to go outside the model (I am fine with using box() and unbox() as needed) I just wanted to understand why it didn't work based on the code I read. Thank you!

**Comment by Lynesth** [comment]
No problem.

What I meant by "inside" the class model is something like this:

```php
class Somebean extends RedBean_SimpleModel {
    public function addToList( Otherbean $ob ) {
        $this->bean->xownOtherbeanList[] = $ob;
        R::store($this->bean);
    }
}

class Otherbean extends RedBean_SimpleModel {
}

// Let's just dispense somebean
$sb = R::dispense( 'somebean' );

// And an otherbean that we box
$ob = R::dispense( 'otherbean' )->box();

// Then we can do
$sb->addToList($ob);
```

Lyn.
