### ISSUE TITLE
Unloading beans

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#582]
In long running processes how can i unload some beans without tainting other beans? Suppose i have

```php
$foo = R::load('foo', 1);
foreach ($foo->ownBarList as $bar) { } // dummy loop so it triggers loading the dat list
```

How do i keep `$foo` but unload all the `bar`s so that they can be garbage collected? This is important for long running processes who want to watch out for memory usage.

I was also wondering if i do something like

```php
$barOne = R::load('bar', 1);
$foo = R::load('foo', 1);
foreach ($foo->ownBarList as $bar) { } // dummy loop so it triggers loading the dat list
```
Where `$foo->ownBarList` also contains the same `bar`, are there two objects created or do they both refer to the same `bar`?

And as general question ... what should i know to prevent memory leaks with redbean?

**Comment by gabordemooij** [comment]
You can empty a list without deleting beans using the noLoad() modifier:

https://redbeanphp.com/index.php?p=/using_sql_snippets

this does not clear the memory though it seems. I have never used RedBeanPHP for long running scripts.

**Comment by gabordemooij** [comment]
It also helps to disable the writer cache

**Comment by krisives** [comment]
In our application we have a "long running process" for background jobs and we use `fresh()` on the "top level bean" since otherwise columns and lists are cached.

**Comment by flip111** [comment]
`fresh` is not ideal here since it does a reload on the database. Can a method be added that has the effect of `fresh` without hitting the database?

**Comment by Lynesth** [comment]
In the case of long running processes, the issue is that RedBean loads everything in arrays. Like if you need to iterate over a list with 2000 items, it'll load all of it in an array before doing anything else. That and PHP poor GC are where your memory usage comes from.

I can only advise you to use PDO for this case, using a while fetch loop. It seems to be the best way to do it.

Here is an example with a table with ~1500 rows.

First using RedBean only:

```php
require 'rb-mysql.php';
R::setup( 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PWD );
R::freeze(true);

$details = R::findAll("details");
foreach ($details as $d) {
}

print memory_get_peak_usage(true);
// Outputs: 7077888 which is 6.75MB
```

The same thing using the PDO version:

```php
require 'rb-mysql.php';

R::setup( 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PWD );
R::freeze(true);
$pdo = R::getPDO();    // useful function here :)

$stmt = $pdo->prepare("SELECT * FROM details");
$stmt->execute();
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    $d = R::convertToBean("details", $row); // And here you still have your bean !
}

print memory_get_peak_usage(true);
// Outputs: 1572864 which is 1.5MB
```

Same thing with a 20k rows table (only 3 columns):

**RedBean only:** 58.5MB
**PDO version:** 1MB

The more the records, the worse it get.

Maybe we need a function to iterate over such records without saving them to an array first, similar to that while fetch loop ? What do you think @gabordemooij ?

**Comment by flip111** [comment]
Maybe the records can be yielded from a generator so that the array interface won't have to change.

**Comment by Lynesth** [comment]
This can actually be done without `getPDO` (we just need to read the docs):

```php
require 'rb-mysql.php';
R::setup( 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PWD );
R::freeze(true);

$details = R::findCollection("details");
while ($d = $details->next()) {
}
```

This works as intended. Docs page here: https://www.redbeanphp.com/index.php?p=/finding#cursors
