### ISSUE TITLE
Undefined index id

### ISSUE THREAD

**Issue by thaodt** [gabordemooij/redbean#586]
Hi gabor,
I'm interested in redbean recently and try to learn how to apply it into my project.

I have 3 questions:

1. I have a snippet below, I used `findCollection()` method, then use the loop `next()` to go through every item. 
As I can see, the item is a bean. How can i retrieve the value from item?
At the moment, i use `export()` method. I just thought I can access it via pointer operator like a object or am i missing any special things?
```
$oCollection = R::findCollection('Document', 'Type = ? LIMIT ? OFFSET ?', [$strDocType, $limit, $i]);
                while ($item = $oCollection->next()) {
                    $arrItem = $item->export();
                    $strUID = $arrItem['UserID'];
}
```
Then i will use `$strUID` to update for the list of records on another table.

2. When i use the `count()` method, why is my table converted into the lower-case first letter with the underscore in the front of the table name? It cannot recognize my table and then return 0.

Can you please show me the right way to do it? Because my tables are the upper-case first letter as above.

3. When i use findCollection() method or any find() method, i always get the warning undefined index 'id'. Then i read the source code and i thought Redbean use default primary key is `id`.

I think it must have a method or sth to set the right ID. Because my fields (columns) are also the uppercase first letter.

Can you please help me clear those?

**Comment by gabordemooij** [comment]
Hi there,

1
You can access bean properties like you access normal object properties:

`$bean->property`

however since beans implement array-acces, this is also allowed:

`$bean['property']`


2/3
Your database schema has to comply with the RedBeanPHP schema policies to work. This means you have to use a primary key 'id' column, or let RedBeanPHP generate the schema for you.

**Comment by thaodt** [comment]
Hi @gabordemooij ,
so for the point 2 & 3, don't we have any methods to map my schema to RedBean schema?

**Comment by Lynesth** [comment]
Since this is still unanswered:

RedBean will use lowercase tables, and a lowercase **id** column and property as the primary key of its bean.

There is currently no way to map your schema for RedBean to use (and I don't think that it is a planned feature), so unless you change your tables and columns names, you won't be able to use RedBean :(
