### ISSUE TITLE
count() warnings thrown from RedbeanPHP\Finder on PHP 7.2

### ISSUE THREAD

**Issue by tommoyangn** [gabordemooij/redbean#611]
[PHP 7.2 requires the first argument of count() to either implement Countable, be an array, or be null](http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types)

**Comment by tommoyangn** [comment]
[Warnings are being thrown in travis-ci](https://travis-ci.org/gabordemooij/redbean/jobs/329323658#L3982), even though it does build:

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/travis/build/gabordemooij/redbean/testing/RedUNIT/Base/Dispense.php on line 147
PHP Stack trace:
PHP   1. {main}() /home/travis/build/gabordemooij/redbean/testing/cli/runtests.php:0
PHP   2. RedUNIT\Base\Dispense->run() /home/travis/build/gabordemooij/redbean/testing/cli/runtests.php:254
PHP   3. RedUNIT\Base\Dispense->testDispenseAll() /home/travis/build/gabordemooij/redbean/testing/RedUNIT.php:81
PHP   4. count() /home/travis/build/gabordemooij/redbean/testing/RedUNIT/Base/Dispense.php:147
Warning: count(): Parameter must be an array or an object that implements Countable in /home/travis/build/gabordemooij/redbean/testing/RedUNIT/Base/Dispense.php on line 147
Call Stack:
    0.0005     459224   1. {main}() /home/travis/build/gabordemooij/redbean/testing/cli/runtests.php:0
   15.8483    3338648   2. RedUNIT\Base\Dispense->run() /home/travis/build/gabordemooij/redbean/testing/cli/runtests.php:254
   15.8529    3341496   3. RedUNIT\Base\Dispense->testDispenseAll() /home/travis/build/gabordemooij/redbean/testing/RedUNIT.php:81
   15.8633    3362696   4. count() /home/travis/build/gabordemooij/redbean/testing/RedUNIT/Base/Dispense.php:147
```

**Comment by tommoyangn** [comment]
My apologies, I didn't notice the warnings thrown in travis-ci are just the test cases. Our own tests emit warnings [on line 242 of Finder.php, within the loop](https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/Finder.php#L242):

```php
public function findLike( $type, $conditions = array(), $sql = '' )
{
	if ( count( $conditions ) > 0 ) {
		foreach( $conditions as $key => $condition ) {
			if ( !count( $condition ) ) unset( $conditions[$key] );
		}
	}
	return $this->redbean->find( $type, $conditions, $sql );
}
```

**Comment by dominics** [comment]
We've been fixing this by changing the count line to accept scalars. So, this:

```php
if ( !count( $condition ) ) unset( $conditions[$key] );
```

becomes

```php
if ( $condition === null || ( is_array( $condition ) && !count( $condition ) ) ) unset( $conditions[$key] );
```

This works because the behavior of count is:

| expr | result |
| --- | --- |
| `count(0)` | 1 |
| `count("")` | 1 |
| `count(false)` | 1 |
| `count([])` | 0 |
| `count(null)` | 0 |

So, you only really need to special case the `null`, and then guard the `count()` call with an `is_array()`. That way, you can still use findLike with scalars as the conditions (rather than requiring an array of arrays like in #612)

**Comment by Lynesth** [comment]
@dominics: The new behavior of count() since PHP7.2 is to throw a warning for anything that's not countable (integers, strings, bools, etc).

If you check the function that actually make SQL from those conditions (```makeSQLFromConditions()```), you'd notice that it expects arrays, and transforms them if needed:

```if ( !is_array( $values ) ) $values = array( $values );```

And, by the way, if you didn't fix the count() from that function, you should still get the warnings.

So we should either use arrays as expected (```[50]``` isn't much longer to write than ```50```) or we'd have to change more stuff.

I'll make another PR fixing it the other way around (closed #612 which wasn't good anyway) by transforming values into arrays if needed.

**Comment by gabordemooij** [comment]
that looks like a fine solution to me

**Comment by dominics** [comment]
> The new behavior of count() since PHP7.2 is to throw a warning for anything that's not countable (integers, strings, bools, etc).

Aware of that, thanks. The snippet I posted never executes `count()` for scalars (thanks to short-circuiting).

> So we should either use arrays as expected ([50] isn't much longer to write than 50) or we'd have to change more stuff.

The interface documentation, as far as it goes, only expects an array of conditions - it doesn't specify that the condition values are also only expected to be arrays (i.e. it's `@param array $conditions` not `@param array[] $conditions`/`@param array<array> $conditions`) So, it's a matter of how much you want to keep BC.

> transforming values into arrays if needed

Awesome, that fixes things perfectly and keeps full BC with code that was working before 7.2.

**Comment by Lynesth** [comment]
@dominics I just read my last comment back and I'm sorry it felt like I was a jerk (english isn't my mother tongue and I sometimes don't convey the right emotions).

I guess I was a bit tired cause I didn't fully grasped your fix, and you're even more right, because the docs actually says this:
```
     * Format of criteria set: property => value
     * The criteria set also supports OR-conditions: property => array( value1, orValue2 )
```

I made another PR for this which I think is much better.
