### ISSUE TITLE
Why isn't usePartialBeans mode active by default?

### ISSUE THREAD

**Issue by alystair** [gabordemooij/redbean#654]
Curious why "usePartialBeans" wouldn't be turned on by default, wouldn't it be more performant? (Novice question)

**Comment by gabordemooij** [comment]
Mainly for backward compatibility. We take BC very serious. RedBeanPHP exists since 2009 and as soon as the tiniest detail changes I get a storm of e-mails complaining about it ;) So, I have to make sure nothing breaks. Besides (but this might be personal) overwriting the entire bean might be easier to reason about. Just replace the whole thing works for most people.

**Comment by alystair** [comment]
Fair enough, I feel there should be something to this regard in the documentation (pro/cons for new projects) - maybe run a benchmark to see if there's a sizeable difference to see if it's worth the effort?

**Comment by gabordemooij** [comment]
Do you think I should add a special block for this on the CRUD-page?

**Comment by alystair** [comment]
Depends on what external parts of redbean it influences the most... eg. does it change the way metadata works at all?

**Comment by gabordemooij** [comment]
What about this:

> By default beans are completely overwritten upon storing. To update only changes of beans use: R::usePartialBeans(TRUE). Completely replacing beans is the default way to store beans in RedBeanPHP and because of backward compatibility this will remain so. It's also very simple to reason about. In some cases you only want to update relevant parts of beans though.

**Comment by gabordemooij** [comment]
I dont know if it's more performant. I think depends on the implementation of the DB engine.
