### ISSUE TITLE
The package version installation should be modified

### ISSUE THREAD

**Issue by peter279k** [gabordemooij/redbean#661]
As title, the `Installation via Composer` section in `README` has this sentences: `(e.g. "gabordemooij/redbean": "dev-master")`.

It should be changed into `(e.g. "gabordemooij/redbean": "^5.1")` because using the stable version is the proper way to do this.

**Comment by gabordemooij** [comment]
Hm, strange. I never use composer but the other composer-users here agreed upon using this sentence. Feel free to send in a pull request.

**Comment by gabordemooij** [comment]
This highlights yet another issue with composer, people can't even agree on how it should be used. It' s a piece of crap and I will remove support for it. I see now that it was a mistake to allow that composer file in the repository.

**Comment by gabordemooij** [comment]
It's generally safe to use the master branch.

**Comment by peter279k** [comment]
@gabordemooij, thank you for your explanation.

At some times, I just want to install the stable released version, not `master` branch version in the production.

I don't think installing the `master` version for the production environment is the proper way :confused:.

**Comment by gabordemooij** [comment]
@peter279k that's why you can download RedBeanPHP as a tarball from the website (those are the official releases).

However with RedBeanPHP the master is quite safe, even for production. The library is very mature and we care a great deal about backward compatibility. Version 5 is almost completely compatible with version 4 for example. There are also no breaking changes on the roadmap.
