### ISSUE TITLE
Documentation of data types

### ISSUE THREAD

**Issue by marios88** [gabordemooij/redbean#668]
https://redbeanphp.com/index.php?p=/crud

```
    //Examples of other data types
    $meeting->when = '19:00:00'; //Time
```
Time does not seem to be supported as a data type

**Comment by Lynesth** [comment]
Hey there,

You're totally right about this. There's actually no detection for TIME data type and I'm pretty sure there never has been any. I guess that's just a miss that wasn't discovered before because not so many people use the TIME data type and I can't think of any reason not to add it.

Feel free to submit a PR on this matter (you can take the DATETIME type as an exemple if you want, try looking for `C_DATATYPE_SPECIAL_DATETIME` in the code).

Lyn.

**Comment by Lynesth** [comment]
@gabordemooij Shouldn't we add the TIME data type ?
