### ISSUE TITLE
Low performance because of data type conversion when using findOne

### ISSUE THREAD

**Issue by brtdv** [gabordemooij/redbean#700]
Hi

I'm noticing performance issues when I'm using `R::findOne('bean', 'property = ?', ["123"])` on a large table.

I've been able to find the origin of the problem but can't seem to fix the issue.

My table `bean` has column `property` that is of type `VARCHAR(100)`. This table has > 1M records. The `property` column is of type `VARCHAR(100)` because it can contain all kinds of data, not only integers. 

However, when I'm using: `R::findOne('bean', 'property = ?', ["123"])`, the following query gets generated in the background: `SELECT bean.*  FROM bean  WHERE property = 123 LIMIT 1`. Redbean seems to convert the `string` value to an `int`. This query takes a long time to finish, even though I have a MySQL `INDEX` set on the `property` column.

Checking the query by using an `EXPLAIN SELECT bean.*  FROM bean  WHERE property = 123 LIMIT 1`, indicates that MySQL is not using the INDEX that I have set, and performs a *simple where* on the table.

Normally, `R::findOne('bean', 'property = ?', ["123"])` should generate `SELECT bean.*  FROM bean  WHERE property = "123" LIMIT 1` (mind the quotes around "123").  This query runs very fast. Examining this query by using `EXPLAIN`, indicates that MySQL is using the INDEX that has been set in the background.

How can I solve this issue? 
I've tried: 
- `R::findOne('bean', 'property = ?', ["123"])`
- `R::findOne('bean', 'property = ?', [strval(123)])`

but everytime, Redbean seems to generate the query without quotes in the background. (`SELECT bean.*  FROM bean  WHERE property = 123 LIMIT 1`).

I'm only having this issue when I use strings that only contain numerical characters. Strings that contain both alpha & numerical characters don't have this issue:
- `R::findOne('bean', 'property = ?', ["abc"])`
- `R::findOne('bean', 'property = ?', ["def"])`
- `R::findOne('bean', 'property = ?', ["a123"])`
- `R::findOne('bean', 'property = ?', ["123b"])`
... etc. work perfectly fast

I know you can use `$bean->setMeta("cast.property","string");` to set the data types of beans when storing them, but that's not really useable in this situation, right?

Another way would be to 
`$result = R::getRow( "SELECT * FROM bean WHERE property = ? LIMIT 1;", ["123"]);` and then convert `$result` to a bean object, but I'm experiencing the same issue, the parameter also gets converted to a numeric value...

A very dirty hack/solution to this problem would be to change my code to: ``R::findOne('bean', 'property = "'.addslashes($value).'"');` but that seems wrong for a lot of reasons...

What would be the best way to solve this issue?

**Comment by marios88** [comment]
I run into this long ago on another system (not redbean), if i remember correctly, mysql will not use indexes for wrong data types.

So try this:
```
R::findOne('bean', 'property = CONCAT(?,'')', ["123"]);
```

**Comment by Lynesth** [comment]
Hey there,

In RedBean, if the parameter can be treated as an int, the pdo function bindParam will be called with the PARAM_INT option.

You can bypass this by setting `R::getDatabaseAdapter()->getDatabase()->setUseStringOnlyBinding(true);` before that query (and setting it back to false after that).

**Comment by brtdv** [comment]
Thank you for the suggestions. 

The answer of @Lynesth is similar to what I was looking for that I could use in this specific case. Right after calling `R::findOne`, I'm setting `useStringOnlyBinding` back to `false`. Thanks!

**Comment by Lynesth** [comment]
To make it clearer, what @brtdv was doing doesn't work because in mysql, if one of the operands of a comparison is an int, it will cast the other operand as an int too.

For example, `SELECT * FROM bean WHERE id = '1abc'` will return the bean with **id = 1** because since `id` is an int, it will cast the string `'1abc'` to an int, which is `1`.

Same goes the other way. Let's take your example and say you have a row where **property = '123xyz'**. Then the following `SELECT * FROM bean WHERE property = 123` will return it because since `123` is an int, it will cast `property` as an int too, and `'123xyz'` becomes `123`. So it cannot use the column index because it needs to cast every value!

-------------------

Knowing this, the only "issue" you should be able to encouter with the current system is: wanting to treat something that looks like an int as a string. And I agree that we should add a way to do it without creating specific functions, something simple that doesn't break BC. I'll make a PR on this.
