### ISSUE TITLE
Poll: proposal R::extract

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#718]
To extract values from a bean hierarchy:

    $titles = R::extract( $book, 'ownPageList.*.title' );

would that make life easier?

**Comment by Lynesth** [comment]
What would this specific example generate (both SQL and return values I mean) ?

**Comment by gabordemooij** [comment]
This would not generate SQL just fetch a deeply nested bean value.

**Comment by marios88** [comment]
Cant you do this with a simple for loop?

**Comment by Lynesth** [comment]
Not sure I understand.What would it do in your example ? Return each title of all the pages in the book ?If the ownPageList isn't loaded it will get it from the db the regular way ?What purpose does the `.*.` serves in the notation ?As marios88 pointed out, isn't a loop more than enough for this ?Le 3 juin 2019 21:20, marios88 <notifications@github.com> a écrit :Cant you do this with a simple for loop?



On Mon, Jun 3, 2019 at 1:13 PM Gabor de Mooij <notifications@github.com>

wrote:

**Comment by gabordemooij** [comment]
Yes you could do it with a loop, it's just a timesaver, I can create a separate library for it as well, it would only be one function.

ownPage.*.title

would loop over all pages and grab the title for each of them.

**Comment by Lynesth** [comment]
Hmm not sure about this really.

Why not make it generate a proper query and execute it ? That way it will be faster and lighter than actually retrieving all the data from the db. Also allow extracting more than one column.

For example, `R::extract($book, 'ownPage.*.[title,number]');` would execute something like `SELECT title, number FROM page WHERE page.book_id = ?` and return the results. (I removed the `.*.` because I don't grasp its usefulness).

I am actually using a small plugin that does something like this already:
```php
// Gets the title of the book with ID 1
R::get('book.1.title');
// Gets the title and number of all pages from a book
R::get('page.[title,number]', ' book_id = ? ', [ $book->id ]);
```

**Comment by gabordemooij** [comment]
It was not my purpose to re-invent SQL, it was just to fetch a value from tree structure (might not even be beans). But I see that it is out-of-scope now.
