### ISSUE TITLE
R::absorb

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/redbean#734]
This feature is nothing more than (in frozen mode):

try {
R::store( $bean )
} catch (..) {
R::freeze( FALSE );
R::store( $bean );
R::freeze( TRUE );
}

It might essentially be a super simple fix for schema caching.
Instead of building a caching system we simply try to insert the been in frozen mode, then if that fails, try again in fluid mode.

https://github.com/gabordemooij/redbean/pull/721

**Comment by Lynesth** [comment]
Not really sure about implementing this feature but wouldn't you prefer adding a `$unfreezeIfNeeded` argument to `R::store` and `R::storeAll` that would do something like you proposed:

```php
public static function store( $bean, $unfreezeIfNeeded = FALSE ) {
    if ( !$unfreezeIfNeeded || !self::$redbean->isFrozen() )
        return self::$redbean->store( $bean );
    try {
        $id = self::$redbean->store( $bean );
    } catch ( RedBeanPHP\RedException\SQL $e ) {
        self::freeze( FALSE );
        $id = self::$redbean->store( $bean );
        self::freeze( TRUE );
    }
    return $id;
}
```

**Comment by gabordemooij** [comment]
Sure yes, that's probably even better.

**Comment by gabordemooij** [comment]
Event better only use this for

R::storeAll( $beans, $unfreezeIfNeeded )

**Comment by Lynesth** [comment]
You don't want it on `R::store` ?

**Comment by gabordemooij** [comment]
Well:

1. R::storeAll is used less than R::store, triggering the new parameter by accident should be less of a problem. Both store() and storeAll() of course do not accept 2nd parameter right now, but people may still pass it accidentally. With storeAll() this seems a little less likely.

2. Additing it to store() means that the parameter for unfreezeIfNeeded also has to be added to storeAll while the other way around is not necessary.

**Comment by marios88** [comment]
Hybrid fluid/frozen mode is a nice feature to have out of the box.

If you go forward with It on `R::store / R::storeAll`, it is more consistent to have it on both functions, since they do the same thing they should accept the same parameters.

`R::absorb / R::absorbAll` goes around both of your objections

**Comment by Lynesth** [comment]
I agree with @marios88 that if we were to add it to `R::storeAll` then it should be added to `R::store`.
However I'm not really in favor of adding yet another couple of `function/functionAll` but since you don't seem keen on adding the parameter to the existing functions, here comes a couple of ideas:

We could add a function which, when called, will apply the unfreezeifneeded mechanic to `store/storeAll`.
```php
R::unfreezeIfNeeded( TRUE );
R::store( $bean );
R::unfreezeIfNeeded( FALSE );
```

Or we could add those to `store/storeAll` and use the new awesome features set to prevent distracted people from making mistakes :)

**Comment by gabordemooij** [comment]
R::useFeatureSet('latest')
    R::store( $bean, TRUE );
    R::storeAll( $beans, TRUE );


Yep looks nice.
