### ISSUE TITLE
Return boolean from R::trash()

### ISSUE THREAD

**Issue by benmajor** [gabordemooij/redbean#736]
At the moment, `R::trash()` returns `void`, even if the trash operation was successful.

It would be more intuitive for `R::trash()` to return a boolean representation of whether the query was successfully executed. For example, consider the following snippet:

```
if( R::trash($collection) )
{
  return $this->response([ 'deleted' => true ]);
}

return $this->errorResponse(500, 4004);
```

Given the above example, `return $this->response([ 'deleted' => true ]);` will never be executed, even if the bean is successfully trashed.

**Comment by Lynesth** [comment]
The query will always be successfully executed. Otherwise it would raise an exception.
You want to know if the bean was deleted, I guess that's something we could add. We'll see what @gabordemooij has to say about it but I'll make a PR anyway.

Meanwhile, here is how you can currently do that:
```php
R::thrash($collection);
if (R::getDatabaseAdapter()->getAffectedRows()) {
    // The collection was deleted
}
```

Note that it doesn't work for `R::trashAll()` as it would only tell you if the last one was deleted.

**Comment by benmajor** [comment]
Yes, sorry. I should have worded that better. I did indeed mean that if the bean was successfully trashed.

It would certainly be a great addition!

**Comment by gabordemooij** [comment]
merged and added unit test

**Comment by benmajor** [comment]
Thanks for the swift action on this. I think it's a great addition to RedBean!
