### ISSUE TITLE
Bugs R::count & GROUP BY

### ISSUE THREAD

**Issue by Avenax** [gabordemooij/redbean#747]
![!1](https://user-images.githubusercontent.com/12481480/64343375-210dcb00-cff5-11e9-95c4-2d243aee510f.png)
return **117**;

`R::count('maclist', 'GROUP BY macid');`
return **3**;

apparently a mistake

**Comment by Lynesth** [comment]
Your query actually returns 117 rows, it does not return 117.
But I'd guess that the first value returned in the first row is 3.

`R::count()` executes `SELECT COUNT(*) FROM table` plus whatever sql you add after that.
It then takes the value from the first cell/row and returns it. That's it.
Using `GROUP BY` prevent your query from returning only one row so that fails to work as you intend it.

If you need to return the number of macs grouped by macid then you should make a custom query and not rely on count.
