### ISSUE TITLE
shorthand function to get bean from sql

### ISSUE THREAD

**Issue by flip111** [gabordemooij/redbean#771]
I use this little function to encapsulate a common pattern. Maybe something like this can be in redbeanPHP code base?

```php
function getBean($type, $sql, $params = []) {
  $row = R::getRow($sql, $params);
  if ($row === []) {
    return null;
  } else {
    return R::convertToBean($type, $row);
  }
}
```

**Comment by Lynesth** [comment]
How is it different than `R::findOne` ?

**Comment by flip111** [comment]
with `findOne` you can only specify the where-clause

**Comment by Lynesth** [comment]
Actually no, you can throw in some sql as you see fit. For example:
```php
$book = R::findOne('book', ' JOIN author ON book.author_id = author.id WHERE author.name = ? AND number_of_pages > ? ORDER BY title ASC ', [ 'Sarah', 150 ]);
```

**Comment by flip111** [comment]
Ah that's cool. It would be good if the documentation added that you are only meant to leave out the SELECT-clause and further JOIN's etc are all accepted

**Comment by flip111** [comment]
by the way ... [meta mask](https://www.redbeanphp.com/index.php?p=/meta_data) is not supported by `findOne`

**Comment by Lynesth** [comment]
Well, it is indeed not supported by `findOne`, but there's no point in adding it since you can't modify the SELECT clause of the query.

**Comment by flip111** [comment]
I think findOne will do in most situations, just a change in the documentation would be welcome

**Comment by gabordemooij** [comment]
Actually, this is not quite correct. You 'can' change the select of a bean, and in some cases this can also be useful. For instance if you want to obtain the total number of records along with a limited selection (for pagination) you could do:

   R::getWriter()->setSQLFilters(
   array('r'=>
        array('book'=>
             array('__meta_total'=>'COUNT(*) OVER()'))),
   FALSE);

Unfortunately this will generate a property __meta_total on the bean. However I could make a small change to set __meta as the default mask instead of NULL in the core to allow meta properties by default, researching this right now...

**Comment by gabordemooij** [comment]
Added this to master branch, you can now send meta data along with beans.

The syntax with setSQLFilters is just a bit clunky though, might need to improve that. Might be useful to adapt R::bindFunc() to accomodate this feature, right now that function uses a protection that restricts you from binding non-existant columns.
