### ISSUE TITLE
Reloading a bean inside a loop

### ISSUE THREAD

**Issue by jawabuu** [gabordemooij/redbean#826]
Hey @gabordemooij ,
Version: RedBeanPHP5.5
I have a bean that may be be updated by another process. I use a loop to check whether an update has been done like below.

```php
$bean= R::findOne( 'table', ' param = ? ', [ $param ] );
$counter = 1;
$max = 3;

while ((in_array($txn->export()['updated_field'], ['',null])) && ($counter< $max))
{
usleep(1500000);
var_dump(["COUNTER" => $counter,  "BEAN" => $bean]);
$bean = R::findOne( 'table', ' param = ? ', [ $param ] );
$bean = $bean->fresh()
$counter++;
}
var_dump($bean);
```
Unfortunately, the bean does returns 'stale'  despite using `$bean->fresh()`. How can I achieve fresh data each time I query inside the loop?

**Comment by Lynesth** [comment]
Hello,

Almost all `SELECT` queries made by RedBean are cached until some other type of query (UPDATE, DELETE, etc) is performed.
Since the "other query" is made by another process, the RedBean loaded in your loop does not know about it and simple keep retrieving the bean from its own cache.

You simply need to call `R::userWriterCache(false);` before your loop, and you don't need to call `fresh()` as it doesn't bypass the cache (we could probably add this as an option).

**Comment by jawabuu** [comment]
Thank you @Lynesth
The $param does not change. Is this along the lines of what you mean?

```php
$bean= R::findOne( 'table', ' param = ? ', [ $param ] );
$counter = 1;
$max = 3;
R::useWriterCache(false);
while ((in_array($txn->export()['updated_field'], ['',null])) && ($counter< $max))
{
usleep(1500000);
var_dump(["COUNTER" => $counter,  "BEAN" => $bean]);
$bean = $bean->fresh()
$counter++;
}
var_dump($bean);
```

**Comment by jawabuu** [comment]
Hey @Lynesth , confirmed above method works. 
What do you think about adding a fag to `$bean->fresh()` to bypass the cache?
i.e. 
```php
$bean->fresh( CACHE = False)
```
You may close this as the issue can be resolved by updating the documentation to inform users of this behaviour.
